contact_links:
  - name: âš ï¸ğŸ•¹ In order to reduce duplicate and low information issues opened, please read the Reporting problems guide before opening a new one.
    url: https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems
    about: âš ï¸ğŸ•¹ In order to reduce duplicate and low information issues opened, please read the *Reporting problems guide* before opening a new one.
